### ISSUE TITLE
Values dont get inserted sometimes.

### ISSUE THREAD

**Issue by osama3101995** [voidbydefault/EasyApplyBot#1]
https://www.linkedin.com/jobs/search/?currentJobId=3599921438

I got stuck at "How comfortable are you working with frontend code? Scale of 1-10"

**Comment by voidbydefault** [comment]
This is one of the specific questions that do not repeat often, so it's not currently supported by the functionality. If the bot is not auto-skipping this job and appears to be stuck, close the application manually so that the bot can move to next job.  

Additionally, any failed jobs are logged and saved in a file named `failed*.csv`. You can refer to this log to manually complete applications or review pending ones that are marked as 'in-progress' on the following webpage: https://www.linkedin.com/my-items/saved-jobs/

**Comment by voidbydefault** [comment]
@osama3101995 I have made minor changes in code to ensure "experience" is entered as a number. You may contact to sync repo if you're using git or otherwise only download `linkedineasyapply.py` and replace with the one you're currently using.
