### ISSUE TITLE
Job Types Not Working Properly

### ISSUE THREAD

**Issue by walid-physics** [voidbydefault/EasyApplyBot#49]
Hi,

My issue is that no matter how i change the job types options it always select only Internship, even when i put it to false and others to true, it only selects Internship.

Thanks,

**Comment by voidbydefault** [comment]
Are you using proper caps like True and False? Because true in Python is not same as True (and false is not False). The issue you've reported is invalid.

Test 1:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/7686ce5a-4aad-4e8f-b037-97531334c3cf)

Test 1 outcome:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/05667c02-a662-40be-b3fd-28da46197ab3)


Test 2:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/c7a37617-0fd1-412d-a205-96f7a6e36e3d)

Test 2 outcome:
![image](https://github.com/voidbydefault/EasyApplyBot/assets/101434467/33289cee-6c5c-4878-bac8-8376a653d183)

Closing.

**Comment by walid-physics** [comment]
Thank you for your reply, but I was not talking about experience level, I was mentioning the job types! And yes of course I'm using True and False.

**Comment by voidbydefault** [comment]
Welcome. 

Can you share the snippet of your `config.yaml` and the partial screenshot of filters on Linkedin? Job type is buried in "All filters" button. Thanks.

**Comment by voidbydefault** [comment]
Update: Your are right, it's a good catch and thanks for reporting. I figured out the issue and will be pushing a fix in a day or two.

**Comment by walid-physics** [comment]
Anytime! Thank you for the app.

**Comment by voidbydefault** [comment]
I have pushed a fix. Please download the new `linkedineasyapply.py` to get going. 

Closing.

**Comment by walid-physics** [comment]
Ok, Thanks man.
